name: Docs

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      - name: Install Hatch
        run: pipx install hatch
      - name: Update git remote
        run: |
          git remote rm origin
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/RichardOberdieck/opti_test.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy docs
        run: hatch run docs:deploy